development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todolists
  pool: 5
  username: root
  password: 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todolists_test
  pool: 5
  username: root
  password: 
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: todolists_production
  pool: 5
  username: root
  password: 
